### ISSUE TITLE
Stuck at Updating Stage

### ISSUE THREAD

**Issue by Exatex** [DanMossa/paliaOnMac-release#1]
Hi, thanks for the repo!

I have been stuck at the Updating stage at 3/13 at 106.25%, and idea?

<img width="365" alt="image" src="https://github.com/DanMossa/paliaOnMac-release/assets/27958998/9aa1a849-8f82-4026-b0ec-91f15b6dbefa">

Thanks!

**Comment by DanMossa** [comment]
Hey! @Exatex
I've worked on having the updates download and install really quickly but there currently isn't a retry mechanism or anything on the downloads.

Close your existing launcher and try this new one (0.1.5) with the fix:
https://github.com/DanMossa/paliaOnMac-release/releases

You can open it and on the main page and click "Update"
