### ISSUE TITLE
"MacOS Sonoma is required" on Sonoma 14.1.1

### ISSUE THREAD

**Issue by monsterfurby** [DanMossa/paliaOnMac-release#11]
I'm running Sonoma 14.1.1 on an M2 15" Macbook Air 2023 and am unable to proceed past the initial screen with the paliaOnMac 0.5.5 version. It seems to fail to detect Sonoma in the installed version and instead just delivers the "MacOS Sonoma is required" message.

**Comment by DanMossa** [comment]
Fixing now!

**Comment by DanMossa** [comment]
@monsterfurby 
Could you open your terminal and type in the following
`sw_vers -productVersion` and post the output here?

**Comment by nzlaura** [comment]
I'm not the above person, but have the same issue and the output from that command is `14.1.1`

**Comment by DanMossa** [comment]
@monsterfurby @nzlaura Thank you for pasting the output!
Fixed in [0.5.6](https://github.com/DanMossa/paliaOnMac-release/releases/tag/0.5.6)

**Comment by nzlaura** [comment]
Thanks so much! Haha I possibly need to update that blog, eek! My very beginner developer skills from several years back.. 😄
