### ISSUE TITLE
Stuck on 32/368 downloading pakchunk0-windowsclient.pak

### ISSUE THREAD

**Issue by bodrey** [DanMossa/paliaOnMac-release#12]
Hello! Thank you for this project <3 

My internet is not very fast. I left the download overnight and at some point the connection was lost. Now the loading does not go beyond step 32/368 downloading pakchunk0-windowsclient.pak

It's possible that something is actually downloading, but I don't see the amount of free disk space changing.

I tried clearing the cache in extras menu, still same after getting to this step. I waited about 30 minutes after reconnecting and restarting the installation.

![image](https://github.com/DanMossa/paliaOnMac-release/assets/34091887/adf121f3-fef1-4469-9282-31447a28c8be)

**Comment by bodrey** [comment]
oh oh wait it's magically fixed ^_^

**Comment by bodrey** [comment]
It may have made a difference whether I clicked the "Install Palia" button after clearing the cache or just waited. Because now it looks like this (the button is active)

![image](https://github.com/DanMossa/paliaOnMac-release/assets/34091887/6284eb05-a84d-40ff-9526-7977b7e4480d)

**Comment by DanMossa** [comment]
@bodrey Hey! Are things working for you at this point?

**Comment by bodrey** [comment]
Yes! As a result, I came to friends who have fast Internet 😅, and over time everything got better (although there was a feeling that somewhere in the middle everything started again, but apparently not)

Thank you so much ^_^
