### ISSUE TITLE
Issues with the AMD Graphics Driver Pop-up

### ISSUE THREAD

**Issue by justsp1ke** [DanMossa/paliaOnMac-release#18]
<img width="559" alt="Screenshot 2024-01-13 at 4 13 16 PM" src="https://github.com/DanMossa/paliaOnMac-release/assets/156553669/3e2c1979-6225-4a8e-b8e0-b18ae2343261">

This image pops up when I press run to open Palia. I dont know what it means this is my first time downloading a wineskin. If i press "no" Palia still opens and it was fine this morning, but this afternoon it crashes after a couple minutes and I cant log into the game it just shows the Palia loading screen without the box to enter your password. Do you know how I can update the AMD and does this have something to do with the launcher or my computer? Thanks.

**Comment by Topener** [comment]
Not sure if those 2 are related, I've had this popup since I started using it, however, I started having 100% crashes only since recently and now can't get in anymore

**Comment by justsp1ke** [comment]
I was able to get back in by uninstalling it and installing it again and havent had any more issues.

**Comment by Topener** [comment]
I had tested that as well, but it didn't work. Turned out I had to also reinstall Whisky completely. Now it works for me too. Not sure what happened then.

**Comment by DanMossa** [comment]
@justsp1ke Hey! This always pops up due to the Mac's graphics card not being officially supported. You can go ahead and click No. :)
