### ISSUE TITLE
Stuttering

### ISSUE THREAD

**Issue by orhunaka** [DanMossa/paliaOnMac-release#19]
I downloaded the game to my M2 Macbook Air, got it running. Amazing!

After creating a character and entering the world, when I got out of the cave, it started stuttering a lot. This did not happen when I was in the cave. I am guessing the objects in the town makes the game stutter like that. Do you know a fix for this?

I never used Whisky before, so I don't know if there are any options such as DXVK, like in CrossOver.

The graphics settings are at medium.
Specs:
macOS Sonoma 14.2.1
M2 Chip
8 GB RAM

**Comment by orhunaka** [comment]
For future notice, I found the DXVK option in the bottle settings in Whisky.

**Comment by DanMossa** [comment]
Hey! The launcher automatically sets these options depending on what DirectX version you're choosing to use. I'd suggest updating Whisky to the latest version and reinstalling Apple's GPTK via Whisky.
