### ISSUE TITLE
New update won't install anymore

### ISSUE THREAD

**Issue by Topener** [DanMossa/paliaOnMac-release#20]
In the past I've had some issues with installing Palia through the installer, but all resolved when I freshly installed Whisky with a new bottle and then installed Palia.

Now however, I tried this as well, and I cannot boot the game after a fresh install. 

<img width="301" alt="Screenshot 2024-03-02 at 17 25 07" src="https://github.com/DanMossa/paliaOnMac-release/assets/1898949/360fb63d-b872-4c01-91ee-0b5b2eabbb1f">

Pressing update after it has been installed checks all files for existence, but stops at a random file or freezes, but never does anything. A fresh install after (I tried a few times) does the same as above. 

Any idea how to solve? Did they change the way they're installing again?

**Comment by DanMossa** [comment]
Hey! There has been an update and the new 0.6.1 version supports the latest Palia version.

The error you're experiencing occurs if there is a drop in internet while it's downloading.

You can either click uninstall and then install again, or you can wait for version 0.6.2 which I'm working on now to find and redownload missing/broken files!

**Comment by DanMossa** [comment]
Fixed in https://github.com/DanMossa/paliaOnMac-release/releases/tag/0.6.2

**Comment by Topener** [comment]
Wow amazing work. Thanks so much. I'll go testing right away and will report back tomorrow!

**Comment by Topener** [comment]
Reporting back. All works as expected. It even redownloaded a few files it apparently hadn't installed/downloaded properly. 

Thanks again!

**Comment by DanMossa** [comment]
@Topener Amazing! Happy to hear :)
