### ISSUE TITLE
Login frozen 

### ISSUE THREAD

**Issue by Steampoweredpug** [DanMossa/paliaOnMac-release#21]
Hey whenever I try to open Palia no music starts and it freezes before I login

**Comment by DanMossa** [comment]
@Steampoweredpug 

I found this from the developers:
> Palia needs a working audio output or it freezes on the login screen. Plug in or turn on any headphones or speakers.

Here are some instructions:
https://support.apple.com/guide/mac-help/change-the-sound-output-settings-mchlp2256/mac#:~:text=On%20your%20Mac%2C%20choose%20Apple,list%20of%20sound%20output%20devices.&text=)%2C%20USB%20speakers%2C%20and%20AirPlay%20devices.

**Comment by Steampoweredpug** [comment]
Heya!

hey so my login is still frozen it does the animations but the login never shows up it feezes then crashes with headphones.
