### ISSUE TITLE
won't reinstall after last patch

### ISSUE THREAD

**Issue by sub-seb** [DanMossa/paliaOnMac-release#24]
hey there, ever since the new patch the other day I can't get palia running again using this launcher

m2 macbook air running sonoma

i delete everything and start fresh, the installation runs but always sticks on downloading some windows pakchunk. it is downloading something but it just never ends, i've left it overnight on my gigabit connection and it does not finish… not sure how to troubleshoot further :\ any help appreciated!

**Comment by sub-seb** [comment]
Ok, update I got it to finish reinstalling but now after the S6 intro screen it just goes to a black screen with bird noises for a minute before crashing out. Tried installing from fresh twice and same result… :((

**Comment by DanMossa** [comment]
@sub-seb Yeah some of those files are huge and it looks like nothing's happening, but I'm glad you were able to get it finished.

Do you have any headphones or audio attached? Palia requires audio enabled when booting.
