### ISSUE TITLE
Game Freezes and Crashes When Opening Quest Menu

### ISSUE THREAD

**Issue by Nxkki2** [DanMossa/paliaOnMac-release#25]
After the recent patch, I noticed I couldn't open up my quests anymore without freezing and having to restart my game entirely. Is anyone else having this issue? I don't know how to fix it.

**Comment by DanMossa** [comment]
@Nxkki2 Could you try hitting `update` on the Launcher and seeing if that fixes things for you?
If it doesn't, it could be worth tapping uninstall and install and seeing if that works!
