### ISSUE TITLE
ClientException: Connection closed while receiving data

### ISSUE THREAD

**Issue by matruk88** [DanMossa/paliaOnMac-release#26]
I got this on 30 minute of installation 
![photo_2024-05-10_22-30-15](https://github.com/DanMossa/paliaOnMac-release/assets/48094693/821c9d37-b00d-40c5-b9fb-35860c002e52)

**Comment by matruk88** [comment]
Cannot join discord server 
![изображение](https://github.com/DanMossa/paliaOnMac-release/assets/48094693/b1ed1227-efef-4b96-853c-db8e9f1bf7a2)

**Comment by DanMossa** [comment]
@matruk88 Hey! These are all internet connection issues. Try restarting your router or computer!
