### ISSUE TITLE
No sound on title screen, login fields don't appear, then black screen and crash

### ISSUE THREAD

**Issue by roskabytes** [DanMossa/paliaOnMac-release#28]
Hi! I've had a break from Palia and just came back for update 0.180. Unfortunately, I've been having issues with the launcher.

Everything's smooth initially - the game launches to the title screen (after Singularity 6 logo screen). However, there's no sound and the login fields never appear, and shortly after the screen goes black and the game closes without any errors or warnings.

I have tried updating both the game and launcher, uninstalling and reinstalling Palia, installing VCRuntime, clearing cache, using another audio output but nothing helped. 

Switching to DirectX 11 instead of 12 makes the screen go black earlier, right after S6 logo instead of after the Palia title screen.

Let me know if any further info could help!

Launcher version: 0.7.1
MacBook M2 Pro 16" 2023
Sonoma 14.5 (23F79)

**Comment by roskabytes** [comment]
Found a fix for anyone looking. Here are the steps:

1. In Extras: Uninstall Whisky
2. In Home: Uninstall. You should get a "No bottle found" message or something similar.
3. Quit PaliaOnMac and reopen it. You should now be asked set up a Whisky bottle (or something along these lines - like the first time you set PaliaOnMac up). 
4. Follow the on-screen instructions as usual until Whisky opens. Then check for updates and update Whisky if you have the option.
5. Proceed with the installation as per instructions. 

Palia's now working normally - sound is back and I get through to login.

**Note: these were my steps, but if you're having this issue I'd recommend trying to simply update Whisky first and seeing if that fixes the issue for you, before reinstalling Palia entirely.**

**Comment by jciscool9** [comment]
Hi,

I'm having the exact same issue, except i hear sound when it opens, but it then black screens and crashes.

Have updated Whisky, and tried re-installing Palia after the update, but it does not work.

Let me know if anyone has any other tips.
Mac M2, Sonoma 14.5, Launcher 0.7.1

**Comment by sub-seb** [comment]
Same here, crash after intro screen. @DanMossa hope you can find an easy way around this, it seems to be something about the recent patches.

**Comment by DanMossa** [comment]
I just released a new update 0.8.1 that should fix this!
Go ahead and tab `Update` or Uninstall and Reinstall!
https://github.com/DanMossa/paliaOnMac-release/releases

**Comment by stephywephy88** [comment]
> Hi,
> 
> I'm having the exact same issue, except i hear sound when it opens, but it then black screens and crashes.
> 
> Have updated Whisky, and tried re-installing Palia after the update, but it does not work.
> 
> Let me know if anyone has any other tips. Mac M2, Sonoma 14.5, Launcher 0.7.1

Did this fix the issue for you? I'm attempting a first-ever install using fresh whiskey and v0.8.1 on Mac M2 Sonoma 14.5 but only get black screen > crash.

**Comment by sub-seb** [comment]
> Did the new version fix the issue for you? I'm attempting a first-ever install using fresh whiskey and v0.8.1 on Mac M2 Sonoma 14.5 but only get black screen > crash.

It's working for me after Dan's update – m2 air, 14.1.2 – seems odd it would not work on a newer version of sonoma… i had just considered updating too but kinda glad I didn't now! any thoughts @DanMossa ?
