### ISSUE TITLE
Run button doesn't work

### ISSUE THREAD

**Issue by smuhlaci** [DanMossa/paliaOnMac-release#3]
I can't start Palia.

I followed the installation steps, I checked the updates. But I can't start the game.

When I checked Whiskey, I couldn't see Palia either, but I'm sure I downloaded the game. It took a day to install and update because my internet speed was slow.

I'm using Apple M1 Pro and Sonoma 14.0(Official release)

**Comment by smuhlaci** [comment]
I've found the files at `[username]/Library/Containers/com.isaacmarovitz.Whisky/Bottles/28264C70-EB74-436F-84B5-C3E11C3BA4F7/drive_c/users/crossover/AppData/Local/Palia`

When I try to run `Client/Palia.exe`, nothing happens. So I tried to extract `Palia-0.165.0.zip` It's `Palia.exe` has worked perfectly. The problem is, since the 0.165 is an old version, I got Error 424

**Comment by DanMossa** [comment]
Fixed in version https://github.com/DanMossa/paliaOnMac-release/releases/tag/0.3.0
