### ISSUE TITLE
Project abandoned? No updates, discord link broken

### ISSUE THREAD

**Issue by sub-seb** [DanMossa/paliaOnMac-release#30]
Just checking @DanMossa if there will be an update or if we should find a new way to play this game?

Appreciate that it's an unpaid hobby project and significant work may be required to get it running with the latest game updates, but some indication would be appreciated!

**Comment by DanMossa** [comment]
Hey! Sorry for the late response! I'll take a look at it later today!

**Comment by DanMossa** [comment]
The Discord seems to still work for me.

I just released a new update 0.8.1 that should fix this!
Go ahead and tab Update or Uninstall and Reinstall!
[DanMossa/paliaOnMac-release/releases](https://github.com/DanMossa/paliaOnMac-release/releases)
