### ISSUE TITLE
Installer won't update

### ISSUE THREAD

**Issue by taylorN91** [DanMossa/paliaOnMac-release#31]
Hello,

I am having issues updating to the latest version. When I click on "Download new version" It does nothing. I am stuck here. Any advice or is there a way to fix this? Thanks! 
![Screenshot 2024-07-13 at 4 19 35 PM](https://github.com/user-attachments/assets/2c69f291-a55d-456a-a1a9-54b7bb518ccb)

**Comment by DanMossa** [comment]
@taylorN91 I was lazy and made the Download new version button just open a link to the page where you can manually download the newest version :)
