### ISSUE TITLE
nothing happens

### ISSUE THREAD

**Issue by compotnaya** [DanMossa/paliaOnMac-release#33]
hi. I don't understand what to do next. I set up the whiskey and it kind of found her. I click install and nothing happens. Tell me, please, what should I do?
<img width="787" alt="Снимок экрана 2024-08-19 в 11 53 40" src="https://github.com/user-attachments/assets/52d00584-586c-4843-9a1a-dac65af282ba">
<img width="797" alt="Снимок экрана 2024-08-19 в 11 53 46" src="https://github.com/user-attachments/assets/7c33677c-62d7-49eb-aa9a-a2907ef6c889">

**Comment by DanMossa** [comment]
Select the Palia bottle and click Install Paila and just wait. Make sure you have enough space on your hard drive.
