### ISSUE TITLE
Screenshots/photo save location?

### ISSUE THREAD

**Issue by roskabytes** [DanMossa/paliaOnMac-release#34]
Hello! Is there a way of accessing screenshots taken with the game's camera feature? I wasn't able to figure it out. Thanks!

**Comment by DanMossa** [comment]
If you open up Whisky, you can then click the button that lets you open your C Drive.
This is apparently the folder stuff is in!

Time%Appdata%*(Local) /Palia /Saved /SceeenShots For Windows
"AppData\Local\Palia\Saved\Screenshots"

Let me know if that ends up helping at all
