### ISSUE TITLE
Update is redownloading everything?

### ISSUE THREAD

**Issue by sub-seb** [DanMossa/paliaOnMac-release#35]
Thanks for your work on this Dan

I haven't played for a while and went to update. It's been two hours and it seems to re-download the whole game, but in some extra slow way idk, rather than just a patch — is that how it's supposed to work?

Don't get me wrong I can wait since this is a good way to play on a technically unsupported platform, but I thought I saw an update which would allow us to update without basically reinstalling?

Much love!

**Comment by DanMossa** [comment]
Hey! Are you using the latest version, 0.9.3?
That version goes through every file and verifies it's up to date, and only redownloads the files that aren't up to date.

**Comment by ar1307** [comment]
Hi!
It doesn't really work to pause or cancel the eternally slow download in between and then resume it later, right? It looks to me like everything starts from the beginning again (version 0.9.3bu).

**Comment by DanMossa** [comment]
Check out the latest release!
