### ISSUE TITLE
Sequoia not supported?

### ISSUE THREAD

**Issue by PriscillaRolvers** [DanMossa/paliaOnMac-release#36]
The launcher is still running after 8 hours the second time around, so I double-checked all the specs. My mac isn't running Sonoma, but Sequoia. Could that be to blame?

**Comment by DanMossa** [comment]
Sequoia should be working! Let me take a look shortly

**Comment by DanMossa** [comment]
Check out the latest release!

**Comment by PriscillaRolvers** [comment]
Unfortunatly, there is no change for me. I have let the launcher run for 4 hours and later for 6 hours, but Palia isn't installed.
