### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by Milsiez** [DanMossa/paliaOnMac-release#37]
It was taking aggeees to download and I saw somewhere on reddit that I could quit it and then re open it, so I did and it looked liked it worked until I pressed run and I got this message
<img width="798" alt="Screenshot 2024-12-12 at 18 52 26" src="https://github.com/user-attachments/assets/b5bc576d-d10c-4446-a122-6fc012e823f8" />

**Comment by DanMossa** [comment]
Check out the latest release!
