### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by ekoekoeko123** [DanMossa/paliaOnMac-release#38]
It works for me but the macbook gets super hot and crashes after a few minutes . Is this a palia problem or is something going wrong? (M3 chip)

**Comment by DanMossa** [comment]
I'd recommend turning down all the graphics settings within the game and see if that helps!

Also some users have an antivirus and that tends to warm the Mac up!

**Comment by ekoekoeko123** [comment]
That helped! Tysm
