### ISSUE TITLE
Version mismatch?

### ISSUE THREAD

**Issue by smuhlaci** [DanMossa/paliaOnMac-release#4]
I downloaded the new version(v0.3.0) but checking for update says there is a newer version. I think 0.2.5 and 0.3.0 are the same versions.

<img width="333" alt="image" src="https://github.com/DanMossa/paliaOnMac-release/assets/5842741/5007d983-3a22-4d5c-90a7-10f9d44fb5bb">

**Comment by DanMossa** [comment]
@smuhlaci You're right! I screwed up the versioning. I updated the latest 0.3.0 to be the correct version!
