### ISSUE TITLE
424 Issue not working after update button hit

### ISSUE THREAD

**Issue by sion9110** [DanMossa/paliaOnMac-release#5]
Hey Dan great experience so far but I am running into that 424 issue and after hitting update manually I am actually not able to sign in still. Did you have any other solutions to get the launcher to update through your launcher workaround?

**Comment by bookiemel** [comment]
hello! also running into this same issue.

**Comment by DanMossa** [comment]
Yup! Palia updated the folder layout of all their stuff.
I'm about to finish releasing a new version of the launcher that'll fix this!

**Comment by DanMossa** [comment]
Fixed in version 0.3.1
https://github.com/DanMossa/paliaOnMac-release/releases
@sion9110 @bookiemel

**Comment by sion9110** [comment]
Works like a charm thank you
