### ISSUE TITLE
Stuck on Downloading: 275/304

### ISSUE THREAD

**Issue by OrchideenSchubser** [DanMossa/paliaOnMac-release#7]
Hi,

I have an issue while the launcher is trying to install Palia. During the installation process the launcher stops at the following:

Dowloading: 275/304
libsodium.dll

How can I fix this?

Thanks in advance!

**Comment by OrchideenSchubser** [comment]
Update:

I managed to get past 275/304 but am now facing a new issue:

![16971197022752972699651332642838](https://github.com/DanMossa/paliaOnMac-release/assets/147645984/44192b02-458b-4c37-b6f2-2073b8802081)

I tried to uninstall and reinstall, same problem.

Please help.

**Comment by DanMossa** [comment]
Looking into it now!

**Comment by DanMossa** [comment]
@OrchideenSchubser https://github.com/DanMossa/paliaOnMac-release/releases
Using 0.5.1 go to the Extras tab and click `Install VCRuntime`.
You'll also need to click `Update` and wait due to the new Palia version.

**Comment by DanMossa** [comment]
@OrchideenSchubser 
Of course and thank you for the kind words!
Using the newest launcher, try hitting update again and then clicking Run when that's finished.

I also recommend going to the Extras tab and making sure you're on DirectX12.

Let me know!

**Comment by OrchideenSchubser** [comment]
Hi again, I reinstalled completely and now it's running - you're an absolute legend mate, thank you so much! Can you advise on what the best settings are for smoothest gameplay?
